# Subtitle Translator Configuration

# Translation settings
translation:
  source_language: "en"
  target_language: "hu"
  
  # Model selection - choose the best available model
  # Using Gemma3 for better performance and availability
  model: "gemma3:latest"
  
  # Alternative models (in order of preference)
  fallback_models:
    - "llama3.2"
    - "llama3.1"
    - "mistral"
  
  # Translation quality settings
  temperature: 0.3  # Lower = more consistent, Higher = more creative
  context_window: 3  # Number of surrounding subtitles for context
  max_retries: 3
  
  # Tone and style preferences
  tone:
    formality: "auto"  # "formal", "informal", "auto" (detect from context)
    style: "natural"   # "natural", "literal", "creative"
    preserve_timing: true  # Keep translations short for subtitle timing
    
  # Language-specific settings
  hungarian:
    use_informal_when_appropriate: true  # Use "te" form for casual conversation
    preserve_english_names: true        # Keep English names unchanged
    handle_contractions: true           # Handle English contractions properly

# Ollama connection settings
ollama:
  host: "localhost"
  port: 11434
  timeout: 300  # Increased timeout for large models (in seconds)

# Processing settings
processing:
  translation_mode: "line-by-line"  # "line-by-line", "batch", "whole-file"
  batch_size: 10      # Number of subtitles to process in parallel
  overlap_size: 2     # Number of entries to overlap between batches for context continuity
  reassess_overlaps: true  # Allow reassessment of previous translations in overlap
  progress_display: true
  backup_original: true
  resume_enabled: true  # Enable resume functionality

# Multi-Model Architecture Settings
multi_model:
  enabled: true  # Enable multi-model architecture
  
  # Context Model - Story understanding and character analysis
  context_model:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.2  # Lower temperature for consistent analysis
    analyze_full_story: false  # Disable to test basic functionality first
    character_profiling: true  # Extract character voice patterns
    formality_detection: true  # Detect formal/informal patterns
    context_window: 5  # Reduce to very small number for testing
    
  # Translation Model - Primary translation with context
  translation_model:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.3  # Balanced temperature for natural translation
    use_context_analysis: true  # Use context model output
    cultural_adaptation: true  # Apply cultural context adaptation
    
  # Technical Validator - Quality scoring and validation
  technical_validator:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.1  # Very low temperature for consistent validation
    grammar_check: true  # Validate grammar and syntax
    naturalness_score: true  # Score translation naturalness
    quality_threshold: 0.7  # Minimum quality score (0.0-1.0)
    
  # Dialogue Specialist - Character voice consistency
  dialogue_specialist:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.25  # Lower temperature for consistency
    voice_consistency: true  # Enforce character voice consistency
    emotional_tone: true  # Preserve emotional tone
    formality_adjustment: true  # Adjust formality per character
    
  # Multi-model pipeline settings
  pipeline:
    parallel_processing: false  # Process models sequentially for now
    quality_consensus: true  # Require quality consensus from multiple models
    fallback_to_single: true  # Fall back to single model if multi-model fails
    
    # Step selection - which steps to run (all enabled by default)
    run_context_analysis: true     # Step 01: Story understanding
    run_translation: true          # Step 02: Primary translation  
    run_validation: true           # Step 03: Quality validation
    run_dialogue_refinement: true  # Step 04: Dialogue polishing
    
    # Performance optimizations
    skip_validation_for_high_confidence: false  # Force validation to always run for testing
    skip_dialogue_refinement: false  # Set to true to skip dialogue specialist for speed
    batch_validation: true  # Validate multiple entries at once for efficiency

# Output settings
output:
  suffix: "{target_lang}"  # e.g., "filename.hu.srt"
  encoding: "utf-8"
  preserve_formatting: true
  
# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "translator.log"
  console: true
