# Subtitle Translator Configuration

# Translation settings
translation:
  source_language: "en"
  target_language: "hu"
  
  # Model selection - choose the best available model
  # Using Gemma3 for better performance and availability
  model: "gemma3:latest"
  
  # Alternative models (in order of preference)
  fallback_models:
    - "llama3.2"
    - "llama3.1"
    - "mistral"
  
  # Translation quality settings
  temperature: 0.3  # Lower = more consistent, Higher = more creative
  context_window: 3  # Number of surrounding subtitles for context
  max_retries: 3
  
  # Tone and style preferences
  tone:
    formality: "auto"  # "formal", "informal", "auto" (detect from context)
    style: "natural"   # "natural", "literal", "creative"
    preserve_timing: true  # Keep translations short for subtitle timing
    
  # Language-specific settings
  hungarian:
    use_informal_when_appropriate: true  # Use "te" form for casual conversation
    preserve_english_names: true        # Keep English names unchanged
    handle_contractions: true           # Handle English contractions properly

# Ollama connection settings
ollama:
  host: "localhost"
  port: 11434
  timeout: 300  # Increased timeout for large models (in seconds)

# Processing settings
processing:
  translation_mode: "line-by-line"  # "line-by-line", "batch", "whole-file"
  batch_size: 10      # Number of subtitles to process in parallel
  overlap_size: 2     # Number of entries to overlap between batches for context continuity
  reassess_overlaps: true  # Allow reassessment of previous translations in overlap
  progress_display: true
  backup_original: true
  resume_enabled: true  # Enable resume functionality

# Multi-Model Architecture Settings
multi_model:
  enabled: true  # Enable multi-model architecture
  
  # Context Model - Story understanding and character analysis
  context_model:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.2  # Lower temperature for consistent analysis
    analyze_full_story: true  # Enable context analysis for full story understanding
    character_profiling: true  # Extract character voice patterns
    formality_detection: true  # Detect formal/informal patterns
    context_window: 5  # Reduce to very small number for testing
    
    # Custom prompt template for context analysis
    prompt_template: |
      Analyze this subtitle text and provide a structured analysis:

      SUBTITLE TEXT:
      {story_text}

      Please analyze and provide:
      1. CHARACTER PROFILES: Identify main characters and their speaking patterns
      2. FORMALITY PATTERNS: Detect formal/informal speech patterns
      3. TECHNICAL TERMS: List important technical or specialized terms
      4. EMOTIONAL ARCS: Identify emotional themes and progressions
      5. STORY SUMMARY: Brief summary of the content

      Respond in a structured format that can be parsed.
    
  # Translation Model - Primary translation with context
  translation_model:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.3  # Balanced temperature for natural translation
    use_context_analysis: true  # Use context model output
    cultural_adaptation: true  # Apply cultural context adaptation
    
    # Custom prompt template for translation
    prompt_template: |
      Translate the following subtitle into Hungarian, considering the context below.

      SUBTITLE:
      {entry_text}

      CONTEXT:
      - Characters: {characters}
      - Formality Patterns: {formality_patterns}
      - Technical Terms: {technical_terms}
      - Emotional Arcs: {emotional_arcs}
      - Story Summary: {story_summary}

      Requirements:
      - Use appropriate formality and character voice.
      - Preserve technical terms and emotional tone.
      - Output only the translated Hungarian subtitle.
    
  # Technical Validator - Quality scoring and validation
  technical_validator:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.1  # Very low temperature for consistent validation
    grammar_check: true  # Validate grammar and syntax
    naturalness_score: true  # Score translation naturalness
    quality_threshold: 0.7  # Minimum quality score (0.0-1.0)
    
    # Custom prompt template for validation
    prompt_template: |
      Evaluate the following Hungarian subtitle translation for grammar, naturalness, and accuracy. Provide a confidence score (0-1), and suggest improvements if needed.

      ORIGINAL ENGLISH:
      {original_text}

      TRANSLATED HUNGARIAN:
      {translated_text}

      Requirements:
      - Rate grammar and naturalness (0-1 scale)
      - Suggest improvements if translation is awkward or inaccurate
      - Output: JSON with keys: confidence, grammar, naturalness, suggestion (if any)
    
  # Dialogue Specialist - Character voice consistency
  dialogue_specialist:
    model: "gemma3n:latest"  # Using gemma3n for all steps
    temperature: 0.25  # Lower temperature for consistency
    voice_consistency: true  # Enforce character voice consistency
    emotional_tone: true  # Preserve emotional tone
    formality_adjustment: true  # Adjust formality per character
    
    # Custom prompt template for dialogue refinement
    prompt_template: |
      Polish the following Hungarian subtitle for natural conversational flow and character voice, considering the context below. Only output the improved Hungarian subtitle, or the original if no improvement is needed.

      SUBTITLE:
      {translated_text}

      CONTEXT:
      - Characters: {characters}
      - Emotional Arcs: {emotional_arcs}
      - Story Summary: {story_summary}
    
  # Multi-model pipeline settings
  pipeline:
    parallel_processing: false  # Process models sequentially for now
    quality_consensus: true  # Require quality consensus from multiple models
    fallback_to_single: true  # Fall back to single model if multi-model fails
    
    # Step selection - which steps to run (all enabled by default)
    run_context_analysis: true     # Step 01: Story understanding
    run_translation: true          # Step 02: Primary translation  
    run_validation: true           # Step 03: Quality validation
    run_dialogue_refinement: true  # Step 04: Dialogue polishing
    
    # Performance optimizations
    skip_validation_for_high_confidence: false  # Force validation to always run for testing
    skip_dialogue_refinement: false  # Set to true to skip dialogue specialist for speed
    batch_validation: true  # Validate multiple entries at once for efficiency
    
    # Batch processing settings (NEW - much faster!)
    batch_translation: true   # Translate multiple entries together (RECOMMENDED)
    batch_size: 10           # Number of entries to translate in one batch
    max_batch_size: 15       # Maximum batch size for very large files

# Output settings
output:
  suffix: "{target_lang}"  # e.g., "filename.hu.srt"
  encoding: "utf-8"
  preserve_formatting: true
  
# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "translator.log"
  console: true
